version: "3.8"
services:
  app:
    build: ./app
    #image?
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ephemeralSecrets
    links:
      - db
    volumes:
      - ./:/src

  db:
    image: mysql:8.0.23
    #cap_add:
    #  - SYS_NICE
    restart: always
    ports:
      - "32000:3306"
    environment:
    #- MYSQL_DATABASE=ephemeralSecrets
    - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql

    #  OLD ONE: - ./db:/docker-entrypoint-initdb.d/:ro

  proxy:
    image: nginx:1.19.10-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginxproxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginxproxy/certs:/etc/nginx/certs
    depends_on:
      - app

volumes:
 db:
   driver: local