version: "3.8"
services:
  # Ephemeral app container.
  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
    # Use environment variables for security and modularity.
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    links:
      - db
    volumes:
      - ./:/src

  # Ephemeral database container.
  db:
    image: mysql:8.0.23
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # Two volumes. 
    # /init.sql initialises the DB, a non-root DB user for the app, and other vital DB functionality.
    # /mysql is used to persist MySQL database data. 
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql

  # Proxy container for HTTPS.
  proxy:
    image: nginx:1.19.10-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginxproxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginxproxy/certs:/etc/nginx/certs
    depends_on:
      - app

# Define a named volume "db" using the local storage driver for data persistence
volumes:
 db:
   driver: local